--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fpm-pl/PiggyCrates_
branches: 
  - pm5
projects:
  PiggyCrates:
    path: ""
    icon: "resources/img/PiggyCrates.gif"
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.1.0
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.5
        branch: "pm5"
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
    lint:
      phpstan: false
...
